config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :topic, only: [:index] do
    member do
      get 'questions'
    end
  end

  patch 'questions/:id', to: 'questions#draft_update', constraints: lambda {|r| r.params[:commit] == 'Draft' }
  patch 'questions/:id', to: 'questions#draft_publish_update', constraints: lambda {|r| r.params[:commit] == 'Publish' }

  resources :questions do
    collection do
      get 'drafts'
      get 'search'
      get 'refresh'
    end
    member do
      get 'publish'
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
    resources :answers,  only: [:new, :create]
  end

  resources :answers,  only: :show do
    member do
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
  end


  resources :comments, only: [:new, :create, :show] do
    resources :comments, only: [:new, :create]
    member do
      get 'reaction'
      get 'report_abuse'
    end
  end

  get "my-profile", to: "users#current_user_profile"

  resources :users do
    resources :notifications, only: [:index]
    member do
      post :set_avatar
      post :set_topics
      get :questions
      get :follow
      get :unfollow
    end
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'signup', to: "users#new"


  controller :password do
    get "forgot-password" => :forgot
    post 'find_user' => :find_user
    get "reset-password" => :reset
    patch "update-password" => :update
  end

  controller :users do
    get :verify
  end

  namespace :api do
    resources :feed, only: [:index]
    resources :topics, only: [:show]
  end

  resources :buy, only: [:index] do
    collection do
      get :payment
      post :charge
    end
  end
  get 'browse', to: "users#browse"

  namespace :admin do
    resources :credit_packs, only: [:index, :new, :create, :edit, :update]
    resources :users, only: [:show, :index] do
      collection do
        patch :refund
      end
      member do
        get :disable
        get :enable
      end
    end
    resources :questions, only: [:index] do
      member do
        get :unpublish
      end
    end
    resources :answers, only: [] do
      member do
        get :unpublish
      end
    end
    resources :comments, only: [] do
      member do
        get :unpublish
      end
    end

  end
  get 'admin', to: "admin#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :ensure_not_logged_in, only: [:new, :create]
  before_action :ensure_logged_in, only: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.try(:authenticate, params[:password])
      if user.verified? && user.disabled?
        redirect_to login_path, notice: "Your account is disabled"
      end
      if user.verified? && !user.disabled?
        session[:user_id] = user.id
        if params[:remember]
          cookies.signed[:user_id] = { value: user.id, expires: Time.current + ENV['remember_me_expiry_days'].to_i.days }
        end
        if user.admin?
          redirect_to admin_path
        elsif user.user?
          redirect_to my_profile_path
        end
      end
      if !user.verified?
        redirect_to login_path, notice: 'Please verify your email first'
      end
    else
      redirect_to login_path, notice: 'Invalid credentials'
    end

      #FIXME_AB: try to reduce if-else nesting
      #FIXME_AB: if user.verified? && user.disabled?
                    #   rediredt
                    #   return
                    # end
  end

  def destroy
    reset_session
    cookies.delete :user_id
    redirect_to login_url, notice: 'Logged out'
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<%= render 'shared/notice' %>
<div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Welcome</h3>
            <p>Login to ask questions and connect with people who contribute unique insights and quality answers</p>
            <%= link_to  "Signup", signup_path, class: "btn" %>
        </div>
        <div class="col-md-9 register-right">
            <h3 class="register-heading">Log In</h3>
            <%= form_tag do %>
            <div class="row register-form">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="form-group">
                      <%= text_field_tag :email, params[:email], placeholder: "Email", class: "form-control" %>
                    </div>
                    <div class="form-group">
                      <%= password_field_tag :password, params[:password],placeholder: "Password", class: "form-control" %>
                    </div>
                    <div class="form-group">
                        <%= check_box_tag :remember, class: "form-check-inputs" %> Remember Me
                    </div>
                     <%= link_to 'Forgot Password', forgot_password_path %><br>
                    <%= submit_tag 'Login', class: 'btnRegister'%>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>