config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :topic, only: [:index] do
    member do
      get 'questions'
    end
  end

  patch 'questions/:id', to: 'questions#draft_update', constraints: lambda {|r| r.params[:commit] == 'Draft' }
  patch 'questions/:id', to: 'questions#draft_publish_update', constraints: lambda {|r| r.params[:commit] == 'Publish' }

  resources :questions do
    collection do
      get 'drafts'
      get 'search'
      get 'refresh'
    end
    member do
      get 'publish'
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
    resources :answers,  only: [:new, :create]
  end

  resources :answers,  only: :show do
    member do
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
  end


  resources :comments, only: [:new, :create, :show] do
    resources :comments, only: [:new, :create]
    member do
      get 'reaction'
      get 'report_abuse'
    end
  end

  get "my-profile", to: "users#current_user_profile"

  resources :users do
    resources :notifications, only: [:index]
    member do
      post :set_avatar
      post :set_topics
      get :questions
      get :follow
      get :unfollow
    end
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'signup', to: "users#new"


  controller :password do
    get "forgot-password" => :forgot
    post 'find_user' => :find_user
    get "reset-password" => :reset
    patch "update-password" => :update
  end

  controller :users do
    get :verify
  end

  namespace :api do
    resources :feed, only: [:index]
    resources :topics, only: [:show]
  end

  resources :buy, only: [:index] do
    collection do
      get :payment
      post :charge
    end
  end
  get 'browse', to: "users#browse"

  namespace :admin do
    resources :credit_packs, only: [:index, :new, :create, :edit, :update]
    resources :users, only: [:show, :index] do
      collection do
        patch :refund
      end
      member do
        get :disable
        get :enable
      end
    end
    resources :questions, only: [:index] do
      member do
        get :unpublish
      end
    end
    resources :answers, only: [] do
      member do
        get :unpublish
      end
    end
    resources :comments, only: [] do
      member do
        get :unpublish
      end
    end

  end
  get 'admin', to: "admin#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/views/shared/_attachment.html.erb
 <% if file.attached? %>
  <% if file.image? %>
    <strong>Attached: </strong><%= file.filename %><br>
    <%= link_to  image_tag(file, size: "200"), url_for(file), target: :_blank %>
  <% else %>
    <strong>Attached: </strong><%= link_to  file.filename, url_for(file), target: :_blank %>
  <% end %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="container alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul>
          <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
  </div>
<% end %>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="container alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong><%= notice %></strong> 
  </div>
<% end %>

app/views/shared/_report.html.erb
<% if logged_in? && !abuseable.reported_by?(current_user) && !abuseable.posted_by?(current_user) %>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#question-report-abuse">
    Report Abuse
  </button>

  <div class="modal fade" id="question-report-abuse" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= message %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <% if abuseable.is_a? Question %>
          <%= form_for abuseable.abuse_reports.new , local: true, url: report_abuse_question_path(abuseable), method: :get do |f| %>
            <div class="modal-body">
              <%= f.text_area :details, class: "form-control" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Report", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% elsif abuseable.is_a? Answer %>
          <%= form_for abuseable.abuse_reports.new , local: true, url: report_abuse_answer_path(abuseable), method: :get do |f| %>
            <div class="modal-body">
              <%= f.text_area :details, class: "form-control" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Report", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% elsif abuseable.is_a? Comment %>
          <%= form_for abuseable.abuse_reports.new , local: true, url: report_abuse_comment_path(abuseable), method: :get do |f| %>
            <div class="modal-body">
              <%= f.text_area :details, class: "form-control" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Report", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% end %>
         
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_vote.html.erb
<% if logged_in? && !question.posted_by?(current_user) %>
  <%= form_for question , url: reaction_question_path(question) ,remote: true, method: :get, html: { class: "vote" } do |f| %>
    <%= f.submit :upvote, class: "btn  upvote", title: question.reactions.upvotes.count, data: { toggle: "tooltip" }  %>
    <span class="reaction_count"><%= question.reaction_count %></span>
    <%= f.submit :downvote, class: "btn  downvote", title: question.reactions.downvotes.count, data: { toggle: "tooltip" }  %>
  <% end %>
<% else %>
  <strong>Votes : </strong><%= question.reaction_count %>
<% end %>