config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :topic, only: [:index] do
    member do
      get 'questions'
    end
  end

  patch 'questions/:id', to: 'questions#draft_update', constraints: lambda {|r| r.params[:commit] == 'Draft' }
  patch 'questions/:id', to: 'questions#draft_publish_update', constraints: lambda {|r| r.params[:commit] == 'Publish' }

  resources :questions do
    collection do
      get 'drafts'
      get 'search'
      get 'refresh'
    end
    member do
      get 'publish'
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
    resources :answers,  only: [:new, :create]
  end

  resources :answers,  only: :show do
    member do
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
  end


  resources :comments, only: [:new, :create, :show] do
    resources :comments, only: [:new, :create]
    member do
      get 'reaction'
      get 'report_abuse'
    end
  end

  get "my-profile", to: "users#current_user_profile"

  resources :users do
    resources :notifications, only: [:index]
    member do
      post :set_avatar
      post :set_topics
      get :questions
      get :follow
      get :unfollow
    end
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'signup', to: "users#new"


  controller :password do
    get "forgot-password" => :forgot
    post 'find_user' => :find_user
    get "reset-password" => :reset
    patch "update-password" => :update
  end

  controller :users do
    get :verify
  end

  namespace :api do
    resources :feed, only: [:index]
    resources :topics, only: [:show]
  end

  resources :buy, only: [:index] do
    collection do
      get :payment
      post :charge
    end
  end
  get 'browse', to: "users#browse"

  namespace :admin do
    resources :credit_packs, only: [:index, :new, :create, :edit, :update]
    resources :users, only: [:show, :index] do
      collection do
        patch :refund
      end
      member do
        get :disable
        get :enable
      end
    end
    resources :questions, only: [:index] do
      member do
        get :unpublish
      end
    end
    resources :answers, only: [] do
      member do
        get :unpublish
      end
    end
    resources :comments, only: [] do
      member do
        get :unpublish
      end
    end

  end
  get 'admin', to: "admin#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id                         :bigint           not null, primary key
#  body                       :text(65535)
#  user_id                    :bigint           not null
#  question_id                :bigint           not null
#  reaction_count             :integer          default(0)
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  popularity_credits_granted :boolean          default(FALSE)
#  published                  :boolean          default(TRUE)
#  marked_abused              :boolean          default(FALSE)
#
class Answer < ApplicationRecord
  include ReactionRecorder
  include Reported
  include Posted
  include BasicPresenter::Concern

  validates :body, presence: true
  validates :question_id, uniqueness: { scope: :user_id }
  validate :question_is_published
  validate :not_published_if_marked_abusive

  belongs_to :user
  belongs_to :question
  has_many :reactions, as: :reactable, dependent: :restrict_with_error
  has_many :comments, as: :commentable, dependent: :restrict_with_error
  has_many :credit_transactions, as: :transactable
  has_many :abuse_reports, as: :abuseable

  after_commit :notify_question_author, on: :create

  scope :order_by_vote, -> {order(reaction_count: :desc)}
  default_scope { where(published: true) }


  def refresh_votes!
    self.reaction_count = reactions.upvotes.count -  reactions.downvotes.count
    check_popularity
    save!
  end

  private def check_popularity
    if reaction_count >= ENV["popular_question_votes"].to_i && !popularity_credits_granted
      grant_credits
      self.popularity_credits_granted = true
    end

    if reaction_count < ENV["popular_question_votes"].to_i && popularity_credits_granted
      revert_credits
      self.popularity_credits_granted = false
    end

  end

  private def grant_credits
    credit_transactions.popular.create(user: user, amount: ENV["popular_question_credits"].to_i)
  end

  private def revert_credits
    credit_transactions.popular.last.reverse_transaction
  end

  private def question_is_published
    if question.draft?
      errors.add(:base, "Parent question is not published")
      throw :abort
    end
  end

  private def notify_question_author
    unless question.user == user
      UserMailer.send_question_answered_mail(self.id).deliver_later
    end
  end

  def mark_abusive!
    self.transaction do
      self.marked_abused = true
      unpublish!
    end
  end
  
  def unpublish!
    self.published = false
    if popularity_credits_granted?
      self.popularity_credits_granted = false
      revert_credits
    end
    save!
  end

  private def not_published_if_marked_abusive
    if marked_abused && published
      errors.add(:base, 'Cannot be published marked abused')
      throw :abort
    end
  end

end

app/controllers/admin/answers_controller.rb
module Admin
  class AnswersController < AdminController

    before_action :find_answer, only: [:unpublish]
    before_action :answer_not_unpublished, only: [:unpublish]

    def unpublish
      if @answer.unpublish!
        redirect_back fallback_location: admin_questions_path, notice: "Answer unpublished"
      else
        redirect_back fallback_location: admin_questions_path, notice: "Answer could not be unpublished"
      end
    end

    private def find_answer
      @answer = Answer.find_by(id: params[:id])
      unless @answer
        redirect_back fallback_location: admin_questions_path, notice: "Answer doesnt exist"
      end
    end

    private def answer_not_unpublished
      unless @answer.published
        redirect_back fallback_location: admin_questions_path, notice: "Already unpublished"
      end
    end
    
  end
end 

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :ensure_logged_in
  before_action :find_published_question, only: [:new, :create]
  before_action :ensure_has_not_been_already_answered, only: [:new, :create]
  before_action :find_answer, only: [:reaction, :show, :report_abuse]
  before_action :ensure_question_is_published, only: [:show, :reaction, :report_abuse]
  before_action :ensure_not_reporting_own_answer, only: :report_abuse

  def new
    @answer = Answer.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    if @answer.save
      redirect_to @answer, notice: t('.answer_posted')
    else
      p @answer.errors
      redirect_to @question, notice: t('.answer_not_posted')
    end
  end

  def show
    redirect_to "#{question_path(@answer.question)}#answer-#{@answer.id}"
  end

  def reaction
    @answer.record_reaction(params[:commit], current_user)
    render json: { reactable: @answer, timestamp: Time.current }
    # redirect_back fallback_location: root_path, notice: t('.reaction_submitted')
  end

  def report_abuse
    abuse_report = @answer.abuse_reports.new(user: current_user, details: params[:abuse_report][:details] )
    if abuse_report.save
      if @answer.reload.marked_abused
        redirect_to @answer.question, notice: t('.marked_as_abused')
      else
        redirect_to @answer, notice: t('.abuse_reported')
      end
    else
      redirect_to @answer, notice: t('.abuse_not_reported')
    end
  end

  private def find_published_question
    @question = Question.published.find_by(url_slug: params[:question_id])
    unless @question
      redirect_back fallback_location: root_path, notice: t('.cannot_find_published_question')
    end
  end

  private def ensure_has_not_been_already_answered
    if @question.answers.find_by(user: current_user)
      redirect_to @question, notice: t('already_answered')
    end
  end

  private def find_answer
    @answer = Answer.find_by(id: params[:id])
    unless @answer
      redirect_back fallback_location: root_path, notice: t('.answer_not_found')
    end
  end

  private def ensure_question_is_published
    if @answer.question.draft?
      redirect_back fallback_location: root_path, notice: t('.question_not_published')
    end
  end

  private def ensure_not_reporting_own_answer
    if current_user == @answer.user
      redirect_back fallback_location: @question, notice: t('.cannot_report_own_answer')
    end
  end

  private def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.erb
<div id="answer-<%= answer.id %>">
  <%= answer.presenter.markdown_body %>
  <br>
  <small> Posted by <%= link_to answer.user.name, answer.user, class: "text-success" %> <%= time_ago_in_words(answer.created_at) %> ago</small><br>
  <% if current_user != answer.user && logged_in? %>
    <%= form_for @question , url: reaction_answer_path(answer) ,remote: true, method: :get, html: { class: "vote" } do |f| %>
      <%= f.submit :upvote, class: "btn  upvote", title: answer.reactions.upvotes.count, data: { toggle: "tooltip" }  %>
      <span class="reaction_count"><%= answer.reaction_count %></span>
      <%= f.submit :downvote, class: "btn  downvote", title: answer.reactions.downvotes.count, data: { toggle: "tooltip" }  %>
    <% end %>
  <% else %>
    <strong>Votes : </strong><%= answer.reaction_count %>
  <% end %>
  <br>
  <% if logged_in? && current_user.admin? &&  answer.published %>
    <span class="btn btn-danger"><%= link_to  "Unpublish", unpublish_admin_answer_path(answer), class: "text-white" %></span>
  <% end %>
  <br>
  <% if logged_in? && !answer.reported_by?(current_user) && !answer.posted_by?(current_user) %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#answer-<%= answer.id %>-report-abuse">
      Report Abuse
    </button>

    <div class="modal fade" id="answer-<%= answer.id %>-report-abuse" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Report Answer</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= form_for @question.abuse_reports.new , local: true, url: report_abuse_answer_path(answer), method: :get do |f| %>
            <div class="modal-body">
                <%= f.text_area :details, class: "form-control" %>
            </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Report", class: "btn btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% if params[:parent_commentable_id].to_i == answer.id && params[:parent_commentable_type] == "Answer" %>
    <div class="reply-btn nested pre-filled text-success">Reply</div>
  <% else %>
    <div class="reply-btn nested text-success">Reply</div>
  <% end %>
  <div class="reply-form">
    <%= form_for [answer, Comment.new] do |f| %>
      <div class="form-group">
        <% if params[:parent_commentable_id].to_i == answer.id && params[:parent_commentable_type] == "Answer" %>
          <%= f.text_area :body, placeholder: "Add a Reply", class: "form-control reply-comment-field", value: params[:comment_body] %>
        <% else  %>
          <%= f.text_area :body, placeholder: "Add a Reply", class: "form-control reply-comment-field" %>
        <% end  %>
      </div>
      <%= f.submit "Reply", class: "btn btn-danger"  %>
    <% end %>
  </div>
     <a data-toggle="collapse" href="#answer-<%= answer.id %>-comments" role="button">
      <span class="badge badge-danger p-2 mt-2"><%= answer.comments.size %> Comments</span>
    </a>
    <div class="comments-answer collapse" id="answer-<%= answer.id %>-comments">
       <% if answer.comments.any?  %>
        <%= render answer.comments.includes(:user) %>
      <% else %>
        <p>No Comments</p>
      <% end %>
    </div>
</div>
<hr class="my-4 border-success">

app/views/answers/_user_answers.html.erb
<% if user_answers.any? %>
  <% user_answers.each do |answer| %>
    <div id="answer-<%= answer.id %>" onClick="location.href='<%= answer_path(answer) %>'">
      <%= link_to  answer.body, answer %>
      <br>    
      <strong>Votes : </strong><%= answer.reaction_count %><br>
    <small>Answered <%= time_ago_in_words(answer.created_at) %> ago</small><br>
    </div>
    <hr class="my-4 border-success">
  <% end %>
<% else %>
  <h5>No Answers</h5>
<% end %>