config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :topic, only: [:index] do
    member do
      get 'questions'
    end
  end

  patch 'questions/:id', to: 'questions#draft_update', constraints: lambda {|r| r.params[:commit] == 'Draft' }
  patch 'questions/:id', to: 'questions#draft_publish_update', constraints: lambda {|r| r.params[:commit] == 'Publish' }

  resources :questions do
    collection do
      get 'drafts'
      get 'search'
      get 'refresh'
    end
    member do
      get 'publish'
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
    resources :answers,  only: [:new, :create]
  end

  resources :answers,  only: :show do
    member do
      get 'reaction'
      get 'report_abuse'
    end
    resources :comments,  only: [:new, :create]
  end


  resources :comments, only: [:new, :create, :show] do
    resources :comments, only: [:new, :create]
    member do
      get 'reaction'
      get 'report_abuse'
    end
  end

  get "my-profile", to: "users#current_user_profile"

  resources :users do
    resources :notifications, only: [:index]
    member do
      post :set_avatar
      post :set_topics
      get :questions
      get :follow
      get :unfollow
    end
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'signup', to: "users#new"


  controller :password do
    get "forgot-password" => :forgot
    post 'find_user' => :find_user
    get "reset-password" => :reset
    patch "update-password" => :update
  end

  controller :users do
    get :verify
  end

  namespace :api do
    resources :feed, only: [:index]
    resources :topics, only: [:show]
  end

  resources :buy, only: [:index] do
    collection do
      get :payment
      post :charge
    end
  end
  get 'browse', to: "users#browse"

  namespace :admin do
    resources :credit_packs, only: [:index, :new, :create, :edit, :update]
    resources :users, only: [:show, :index] do
      collection do
        patch :refund
      end
      member do
        get :disable
        get :enable
      end
    end
    resources :questions, only: [:index] do
      member do
        get :unpublish
      end
    end
    resources :answers, only: [] do
      member do
        get :unpublish
      end
    end
    resources :comments, only: [] do
      member do
        get :unpublish
      end
    end

  end
  get 'admin', to: "admin#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/credit_pack.rb
# == Schema Information
#
# Table name: credit_packs
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  price      :integer
#  credits    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CreditPack < ApplicationRecord
  #FIXME_AB: add enabled disabled to credit packs only enabled packs will be display to user and only enabled packs can be purchased

  validates :name, presence: true
  validates :price, presence: true
  validates :credits, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 1}, if: -> {price.present?}
  validates :credits, numericality: {greater_than_or_equal_to: 1},if: -> {credits.present?}
  validate :cover_image_attached

  scope :enabled, -> { where(disabled: false) }
  has_one_attached :cover_image

  def create_credit_transaction(user)
    user.credit_transactions.create(amount: credits, transaction_type: CreditTransaction.transaction_types[:purchase], transactable: user)
  end

  private def cover_image_attached
    unless self.cover_image.attached?
      errors.add(:base, "Cover image should be present")
    end
  end

end

app/controllers/admin/credit_packs_controller.rb
module Admin
  class CreditPacksController < AdminController

    before_action :find_credit_pack, only: [:edit, :update]

    def index
      #FIXME_AB: show enabled or disabled in view
      #FIXME_AB: show button to add new pack
      #FIXME_AB: give option to enable or disable a pack
      @credit_packs = CreditPack.all
    end

    def new
      @credit_pack = CreditPack.new
    end

    def create
      @credit_pack = CreditPack.new(credit_pack_params)

      if @credit_pack.save
        redirect_to admin_credit_packs_path, notice: 'Credit Pack created'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @credit_pack.update(credit_pack_params)
        redirect_to admin_credit_packs_path, notice: "Pack updated"
      else
        render :edit
      end
    end

    private def find_credit_pack
      @credit_pack = CreditPack.find_by(id: params[:id])
      unless @credit_pack
        redirect_to admin_credit_packs_path, notice: "Credit Pack does not exists"
      end
    end

    private def credit_pack_params
      params.require(:credit_pack).permit(:name, :price, :credits, :cover_image, :disabled)
    end
  end
end

app/views/admin/credit_packs/_credit_pack.html.erb
<tr class="table-success">
  <td><%= credit_pack.name %></td>
  <td><%= credit_pack.price %></td>
  <td><%= credit_pack.credits %></td>
  <td><%= credit_pack.disabled? %></td>
  <td><%= link_to "Edit Pack", edit_admin_credit_pack_path(credit_pack), class:"badge-danger badge" %></td>
</tr>

app/views/admin/credit_packs/edit.html.erb
<div class="display-container">
  <%= render 'shared/errors', object: @credit_pack %>
    <div class="w-25">
        <%= form_with model: @credit_pack, local: true, url: admin_credit_pack_path do |form| %>
            <div class="form-group">
                <strong>Name:</strong>
                <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
            </div>
            <div class="form-group">
                <strong>Credits:</strong>
                <%= form.text_field :credits, placeholder: "Credits",  class: "form-control"  %>
            </div>
            <div class="form-group">
                <strong>Price:</strong>
                <%= form.text_field :price, placeholder: "Price",  class: "form-control"  %>
            </div>
            <strong> Disabled : </strong><%= form.check_box :disabled %>
            <div class="form-group">
                <strong>Cover image:</strong>
                <%= form.file_field :cover_image,  class: "form-control-file" %>
            </div>
            <%= form.submit 'Update Pack', class: 'btn btn-danger'%>
        <% end %>
    </div>
</div>

app/views/admin/credit_packs/index.html.erb
<div class="display-container">
  <%= render "shared/notice" %>
  <table class="table table-hover table-primary w-50">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Credits</th>
        <th scope="col">Disabled</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= render @credit_packs %>
    </tbody>
  </table>
  <%= link_to "Create New Credit Pack", new_admin_credit_pack_path %>
</div>

app/views/admin/credit_packs/new.html.erb
<div class="display-container">
  <%= render 'shared/errors', object: @credit_pack %>
    <div class="w-25">
        <%= form_with model: @credit_pack, local: true, url: admin_credit_packs_path do |form| %>
             <div class="form-group">
                <strong>Name:</strong>
                <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
            </div>
            <div class="form-group">
                <strong>Credits:</strong>
                <%= form.text_field :credits, placeholder: "Credits",  class: "form-control"  %>
            </div>
            <div class="form-group">
                <strong>Price:</strong>
                <%= form.text_field :price, placeholder: "Price",  class: "form-control"  %>
            </div>
            <strong> Disabled : </strong><%= form.check_box :disabled %>
            <div class="form-group">
                <strong>Cover image:</strong>
                <%= form.file_field :cover_image,  class: "form-control-file" %>
            </div>
            <%= form.submit 'Create Pack', class: 'btn btn-danger'%>
        <% end %>
    </div>
</div>